<?php

declare(strict_types=1);

namespace Componenta\Policy;

/**
 * Configuration keys consumed by {@see PolicyEnforcerFactory} and {@see PolicyProviderFactory}.
 */
final class ConfigKey
{
    public const int CACHE_VERSION = 1;

    public const string POLICY = 'policy';

    /**
     * Action-to-policy factory map for {@see \Componenta\Policy\Provider\ArrayPolicyProvider}.
     *
     * Shape: array<string, PolicyInterface|callable(\Psr\Container\ContainerInterface): PolicyInterface>.
     * Each callable is resolved lazily with the container.
     */
    public const string POLICIES = 'policies';

    /**
     * Action-to-policy descriptor map generated by discovery:compile.
     *
     * This mirrors attribute-discovered policies without doing reflection on
     * the request hot path. AttributePolicyProvider remains the fallback for
     * actions missing from this map.
     */
    public const string COMPILED_POLICIES = 'compiled_policies';

    /**
     * Sidecar file containing the discovery-compiled policy descriptor map.
     */
    public const string COMPILED_POLICIES_FILE = 'compiled_policies_file';

    /**
     * Whether invalid compiled descriptors should throw instead of falling back.
     *
     * Defaults to false so stale generated cache can fall back to attributes.
     */
    public const string COMPILED_POLICIES_STRICT = 'compiled_policies_strict';

    /**
     * Additional provider class names, each resolved through the container.
     *
     * Shape: list<class-string<PolicyProviderInterface>>.
     */
    public const string PROVIDERS = 'providers';

    /**
     * Fallback for missing policies. Defaults to {@see MissingPolicyBehavior::DENY}.
     */
    public const string MISSING_POLICY_BEHAVIOR = 'missing_policy_behavior';
}